export default {
automationexercisePage: 'https://automationexercise.com/',
signupLoginButton: '[href="/login"]',
signupButton: '[data-qa="signup-button"]',
newUserSignup: '.signup-form > h2',
nameSignup:'[data-qa="signup-name"]',
emailSignup:'[data-qa="signup-email"]',
titleSignup: '#id_gender1',
days:'[data-qa="days"]',
months:'[data-qa="months"]',
years: '[data-qa="years"]',
password: '[data-qa="password"]',
newsletter: '[id="newsletter"]',
receviOfeers: '[id="optin"]',
firstName: '[data-qa="first_name"]',
lastName:'[data-qa="last_name"]',
adressRegister: '[data-qa="address"]',
country:'[data-qa="country"]',
state: '[data-qa="state"]',
city:'[data-qa="city"]',
phoneNumber:'[data-qa="mobile_number"]',
zipCode:'[data-qa="zipcode"]'
};